#!/bin/bash
# Starts the infinite loop in the background and kills it using SIGTERM

./4-to_infinity_and_beyond &
pid=$!

sleep 2  # Optional: Give the background process time to start

kill -15 "$pid"
